name: testing
on: [push]

jobs:
    run-testing:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v3
          - name: echo string
            run:  echo "helloworld"
          - name: multiline-script
            run: |
                node -v

