name: testing
on: [push]

jobs:
    run-new-script:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v3
          - name: echo string
            run:  echo "helloworld"
          - name: multiline-script
            run: |
                node -v

    run-another-testing:
        runs-on: windows-latest
        steps:
          - name: Directory
            run: Get-Location
          - name: Directory usung bash
            run: pwd
            shell: bash
