name: shell

on: [push]

jobs:
run-shell
runs-on: ubuntu-latest
steps:
-name: checkout
uses: actions/checkout@v3
-name: echo string
run: echo "hello"
-name: multiline script
run: |
   node -v
           pwd