name: shell command

on: [push]

jobs:
 run-windows-commands:
    runs-on: windows-latest
    steps:
     - name: Directory
       run: Get-location
     - name: Directory using bash
       run: pwd
       shell: bash 
 run-shell-command:
    runs-on: ubuntu-latest
    needs: ["run-windows-commands"]
    steps:
     - name: checkout
       uses: actions/checkout@v3
     - name: echo string
       run: echo "hello"
     - name: multiline script
       run: |
        node -v
         pwd    
