name: shell command

on: [push]

jobs:
 run-windows-commands:
    runs-on: windows-latest
    steps:
     - name: Directory
       run: Get-location
     - name: Directory using bash
       run: pwd
       shell: bash 